[project]
name = "poe-breakout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "isort>=8.0.1",
    "numpy>=2.4.4",
    "poethepoet>=0.42.1",
    "pytest>=9.0.2",
    "ruff>=0.15.8",
]

[tool.poe]
poetry_command = ""
executor.type = "virtualenv"

[tool.poe.env]
PYTHONPATH = "${POE_ROOT}/src"

[tool.ruff]
line-length = 120

[tool.poe.tasks.cleanup]
help = "Run all cleanup tasks"
control.expr = "check" # There is no pass through option (yet?) so use a control expression to pass --check option to tasks when relevant
args = [{name = "check", type="boolean", help= "Does not correct files, only warns"}]
# NB: ruff needs the linter (which will sort imports) to run before the formatter (which cannot sort imports).
  [[tool.poe.tasks.cleanup.switch]]
  case     = "True"
  sequence = ["lint --check", "format --check", "sort --check"]
  [[tool.poe.tasks.cleanup.switch]]
  sequence = ["lint", "format", "sort"]
ignore_fail = true


[tool.poe.tasks.lint]
help = "Lint code (with ruff)"
# --no-fix does override --fix in ruff, if --check is given to poe.
cmd = 'ruff check --fix --show-fixes ${check:+ --no-fix}'
args=[{name = "check", type="boolean", help= "Does not correct files, only warns"}]

[tool.poe.tasks.format]
help = "Format code (with ruff)"
cmd = 'ruff format ${check:+ --diff}'
args=[{name = "check", type="boolean", help= "Does not correct files, only warns"}]

[tool.poe.tasks.sort]
help = "Sort imports (with ruff)"
cmd = 'ruff check --select I --fix --show-fixes ${check:+ --no-fix}'
args=[{name = "check", type="boolean", help= "Does not correct files, only warns"}]

[tool.poe.tasks.tests]
help = "Run tests"
cmd = "pytest"

[tool.poe.tasks.aws]
help = "Connect to AWS (aws sso login)"
cmd = "aws sso login"

[tool.poe.tasks.connect]
script = "local.connect_to_a_database:connect"
help = "Connect to a very real database"
